export const ACTION_TYPES = {
  CREATE_TODO_STARTED: "CREATE_TODO_STARTED",
  CREATE_TODO_SUCCESS: "CREATE_TODO_SUCCESS",
  CREATE_TODO_RESET: "CREATE_TODO_RESET",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
};

export const SAGA_ACTIONS = {
  CREATE_TODO: "CREATE_TODO",
  DELETE_TODO: "DELETE_TODO",
};
